OPENAI_API_KEY="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"
OPENAI_MODEL = "gpt-4"
NEO4J_URI="neo4j+s://535cd1e1.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="LhdP2T9zKDEDreP27zKLXffCIypfEoExIYGfLTufxtU"